import { deploymentGroups } from './wazuh-lessons.ts';
import { stageTime } from './course-timing.ts';
export type RoadmapStage = {
  id: string;
  title: string;
  desc: string;
  time: string;
  tag: string;
  icon: string;
  lessonIds: string[];
  later?: boolean;
  plan?: string[];
};
export const buildLessonIds = [
  'assignment-v2',
  'windows-tools-v2',
  'azure-scope-v2',
  'two-host-plan-v3',
  'resource-group-v2',
  'network-plan-v2',
  'build-storage-v3',
  'nsg-v2',
  'key-concept-v2',
  'key-create-v2',
  'vm-provision-v2',
  'manager-vm-v3',
  'reachability-v2',
  'host-trust-v2',
  'first-ssh-v2',
  'identity-v2',
  'host-os-v2',
  'guest-network-v2',
  'home-files-v2',
  'storage-verify-v3',
  'paired-access-v3',
];
export const transferLessonIds = [
  'test-file-v3',
  'scp-test-v3',
  'verify-transfer-v3',
  'sftp-test-v3',
];
export const prechangeLessonIds = [
  'installer-types-v3',
  'software-inventory-v3',
  'baseline-v2',
  'rollback-gate-v3',
  'deallocate-v2',
];
export const preparationLessonIds = [
  ...buildLessonIds,
  ...transferLessonIds,
  ...prechangeLessonIds,
];
export const lessonOrder = [
  ...preparationLessonIds,
  ...Object.values(deploymentGroups).flat(),
];
export const modules: RoadmapStage[] = [
  {
    id: 'build',
    title: 'Build and administer both RHEL systems',
    desc: 'Windows → Azure → VM/storage choices → rexuser → restricted SSH and verified access to the endpoint and central host.',
    time: stageTime(buildLessonIds),
    tag: 'MAIN LAB · BUILD',
    icon: 'terminal',
    lessonIds: buildLessonIds,
  },
  {
    id: 'transfer',
    title: 'Deliver and verify a harmless file',
    desc: 'Practice SCP and SFTP; verify paths, ownership, permissions, file type, and SHA-256 across Windows and RHEL.',
    time: stageTime(transferLessonIds),
    tag: 'MAIN LAB · DELIVERY',
    icon: 'file',
    lessonIds: transferLessonIds,
  },
  {
    id: 'prechange',
    title: 'Baseline, inspect and approve rollback',
    desc: 'Understand installer forms; inventory packages/services; define and protect the recovery point before any Wazuh installation.',
    time: stageTime(prechangeLessonIds),
    tag: 'MAIN LAB · PRE-CHANGE',
    icon: 'rollback',
    lessonIds: prechangeLessonIds,
  },
  {
    id: 'central',
    title: 'Build the Wazuh central server/dashboard',
    desc: 'Next: install the supported central components on the manager VM, protect credentials, discover services, and validate dashboard access.',
    time: stageTime(deploymentGroups.central),
    tag: 'MAIN LAB · CENTRAL SERVER',
    icon: 'shield',
    lessonIds: deploymentGroups.central,
    plan: [
      'Entry gate: both hosts verified, harmless transfer complete, actual stable release and official artifact trust established, and the recovery plan approved. Recheck current supported RHEL version and central sizing; never use a floating latest instruction without recording the selected release.',
      'Obtain the official central installer using the approved source, inspect its actual file type and vendor integrity evidence, and read its changes before sudo execution. Install manager, indexer, and dashboard together on the central VM only; protect generated credentials and certificates.',
      'Compare package and unit inventories to discover actual services, inspect their files/status/journals, and check enabled versus active state. Then restrict dashboard HTTPS to the workstation source /32 and verify TLS identity and an authenticated dashboard session. Do not expose indexer/API endpoints publicly.',
      'Validate the central system and retain its recovery checkpoint. A healthy dashboard is a milestone, not proof that an endpoint has enrolled.',
    ],
  },
  {
    id: 'agent',
    title: 'Deploy, discover and connect the endpoint agent',
    desc: 'Obtain/transfer/inspect the real RPM, install on the endpoint, discover its service, and configure the private manager destination.',
    time: stageTime(deploymentGroups.agent),
    tag: 'MAIN LAB · ENDPOINT AGENT',
    icon: 'shield',
    lessonIds: deploymentGroups.agent,
    plan: [
      'Entry gate: healthy central server and an endpoint-specific pre-agent checkpoint. Revalidate the rollback plan immediately before installing, even if manager setup changed the environment after the earlier checkpoint.',
      'Use the approved vendor package and record version/architecture/signature. Transfer or retrieve it, identify its type, compare the digest to a trusted reference, and inspect the DNF transaction before sudo installation. Do not use chmod +x as the RPM installation method.',
      'Ask “what did it install?” Compare rpm -qa and systemd inventories; rpm -ql on the discovered package locates unit/configuration files. Identify the actual unit before using status, start/enable, or journalctl. Explain every selected option and privilege.',
      'Set the endpoint’s manager destination to the recorded private address or correctly resolved name. Use the chosen release’s supported enrollment procedure, protect any enrollment secret, and verify only the required private-network rules. Current defaults use TCP 1514 for events and TCP 1515 for enrollment; do not assume UDP or open unrelated ports.',
    ],
  },
  {
    id: 'checkin',
    title: 'Prove centralized check-in and validate the change',
    desc: 'Correlate endpoint evidence with the dashboard’s enrolled identity, recent check-in, and expected event behavior.',
    time: stageTime(deploymentGroups.checkin),
    tag: 'MAIN LAB · VALIDATION',
    icon: 'activity',
    lessonIds: deploymentGroups.checkin,
    plan: [
      'Record the agent’s actual ID/name and endpoint hostname/private IP. Correlate them with the dashboard record; do not accept a stale same-named agent as proof.',
      'Verify installed package, active/enabled service as appropriate, correct manager address, successful network path, relevant logs, and a recent centralized check-in timestamp. Explain why registration and a presently active connection are different states.',
      'Perform an approved harmless event/telemetry check and correlate its timestamp across endpoint and manager. Compare failed units, storage, access, and expected function to the baseline.',
      'CHANGE WORKS → validate → document evidence, versions, IDs, exceptions, and retention → close the change.',
    ],
  },
  {
    id: 'fault',
    title: 'Diagnose an agent that does not check in',
    desc: 'A controlled, reversible wrong-manager-address exercise. Investigate each layer before changing firewalls or SELinux.',
    time: stageTime(deploymentGroups.fault),
    tag: 'MAIN LAB · TROUBLESHOOT',
    icon: 'activity',
    lessonIds: deploymentGroups.fault,
    plan: [
      'Exercise setup after a working check-in: capture current configuration and timestamps, approve a brief outage, and change only the disposable endpoint’s manager destination to a verified unused/unreachable lab address. Record the original value and restore instruction. Never break SSH or disable security controls to simulate a fault.',
      '1. Installed? Query the actual package with rpm -q; -q is a query, not installation. Confirm package/transaction evidence before network troubleshooting.',
      '2. Running? systemctl status ACTUAL_UNIT --no-pager inspects the discovered service without changing it; compare runtime and enabled state.',
      '3. Logs? journalctl -u ACTUAL_UNIT -n 50 --no-pager filters that unit and the latest 50 entries. Inspect product log files identified from the installation as well; preserve timestamps and redact secrets.',
      '4. Address? Read the application’s configured manager address and compare with the inventory and saved working config. A running service pointed at the wrong host still cannot check in.',
      '5. DNS? getent hosts MANAGER_NAME queries the system name-service path. Only use a name when the lab has DNS configured; compare its answer to the recorded private manager address.',
      '6. Route? ip addr checks guest addresses; ip route get MANAGER_PRIVATE_IP shows selected route/source for that destination. Verify Azure NIC and effective routes too.',
      '7. Port? Use an approved nc implementation (on RHEL commonly supplied by nmap-ncat): nc -vz -w 3 MANAGER_PRIVATE_IP ACTUAL_TCP_PORT performs a verbose, no-data TCP probe with a three-second timeout. On the manager, sudo ss -lntp lists listening (-l) numeric (-n) TCP (-t) sockets and owning processes (-p). A TCP handshake is not application enrollment. curl -I https://DASHBOARD_HOST checks HTTPS response headers only; it is not a test of the agent event protocol, and TLS errors should be investigated rather than bypassed.',
      '8. Azure NSG? Check effective NIC/subnet rules, direction, source/destination and priority on both hosts. Compare to the actual configured protocol/port. Do not expose private application ports to the internet.',
      '9. Guest firewall? firewall-cmd --get-active-zones identifies applied zones; sudo firewall-cmd --zone=ACTUAL_ZONE --list-all inspects that zone. Read before editing; runtime and permanent rules differ.',
      '10. SELinux? getenforce reports mode. sudo ausearch -m AVC,USER_AVC -ts recent searches recent audit denial messages where auditing is available. Correlate process/path/time and correct labels or supported policy as appropriate; do not default to disabling SELinux or blindly generating allow rules.',
      '11. Application configuration? Check syntax, version compatibility, enrollment trust/secrets, and product logs using the chosen release’s documentation. Preserve the working config before a targeted correction.',
      '12. Central registration? Confirm the manager has the expected enrolled agent identity and current connection; resolve duplicate/stale records under the documented procedure. Restore the saved manager destination, retest check-in, and document the actual cause.',
      'If risk grows or the time limit expires: stop, execute the approved rollback, and validate restored health. The final full exercise will include exact selected package/unit names and assessed evidence.',
    ],
  },
  {
    id: 'recover',
    title: 'Practice recovery and document the result',
    desc: 'Agent uninstall, residual configuration/enrollment cleanup, approved restoration, and post-rollback validation.',
    time: stageTime(deploymentGroups.recover),
    tag: 'MAIN LAB · CLOSE',
    icon: 'rollback',
    lessonIds: deploymentGroups.recover,
    plan: [
      'Choose the approved branch: fix and retest, or stop and rollback. Preserve logs, configuration, package/version, and enrollment evidence first.',
      'Inspect the selected release’s uninstall instructions and proposed removal transaction. Remove only intended packages; separately handle lab-owned configuration, service overrides, repositories, logs/keys, and central enrollment records. Do not equate package removal with total cleanup.',
      'Where uninstall cannot restore the required state, follow the tested snapshot/backup restore procedure with correct consistency and compatibility. Reconcile the endpoint identity with the manager after restoration.',
      'Validate rexuser access, expected packages/services, failed units, mounts/capacity, network/DNS/firewall/SELinux state, and central records. Record what was restored, residual exceptions, evidence, retention, and deallocation of both VMs.',
    ],
  },
  {
    id: 'storage-deep',
    title: 'Advanced storage and LVM',
    desc: 'After the deployment scenario: LVM, filesystems, mount options, growth, failure diagnosis and recovery.',
    time: 'Later deep dive',
    tag: 'AFTER THE MAIN LAB',
    icon: 'cloud',
    lessonIds: [],
    later: true,
  },
  {
    id: 'linux-deep',
    title: 'Linux administration in depth',
    desc: 'Users/groups, permissions, packages/repositories, shell scripting, processes, and systemd after practical deployment experience.',
    time: 'Later deep dive',
    tag: 'AFTER THE MAIN LAB',
    icon: 'terminal',
    lessonIds: [],
    later: true,
  },
  {
    id: 'network-deep',
    title: 'Networking and security policy in depth',
    desc: 'Routing, DNS, firewalling and SELinux: deeper diagnostics and controlled configuration changes.',
    time: 'Later deep dive',
    tag: 'AFTER THE MAIN LAB',
    icon: 'cloud',
    lessonIds: [],
    later: true,
  },
  {
    id: 'stig',
    title: 'STIG hardening and assessment',
    desc: 'STIG-minded hardening, SCC/SCAP scanning, export scan results to Windows, and STIG Viewer review.',
    time: 'Later deep dive',
    tag: 'AFTER THE MAIN LAB',
    icon: 'shield',
    lessonIds: [],
    later: true,
  },
  {
    id: 'vulnerability',
    title: 'ACAS and Tenable Security Center',
    desc: 'Authorized vulnerability-management workflow, evidence review, remediation and reassessment.',
    time: 'Later deep dive',
    tag: 'AFTER THE MAIN LAB',
    icon: 'activity',
    lessonIds: [],
    later: true,
  },
  {
    id: 'images',
    title: 'Turn a hardened baseline into a reusable image',
    desc: 'Hardened RHEL baseline, reusable Azure image, and the vSphere golden VM/template workflow with platform-specific differences.',
    time: 'Later deep dive',
    tag: 'AFTER THE MAIN LAB',
    icon: 'rollback',
    lessonIds: [],
    later: true,
  },
];
export const primaryFlow = [
  'Windows administrative workstation',
  'Azure lab planning',
  'Create Azure networking',
  'Create the Linux VMs — prepare the build',
  'Configure storage/partitions during build where practical',
  'Create/use rexuser as the RHEL administrator',
  'Allow SSH only from the current public IP',
  'Generate/use SSH keys from Windows',
  'Authorize the public key for rexuser and submit the VM build',
  'Test SSH access',
  'Practice SCP/SFTP transfer',
  'Establish the pre-change baseline',
  'Define rollback before software installation',
  'Build/configure Wazuh central server/dashboard',
  'Obtain/deploy the Wazuh endpoint agent',
  'Discover and verify the installed service',
  'Configure communication with the manager',
  'Verify dashboard check-in',
  'Troubleshoot failed communication',
  'Validate the completed change',
  'Practice rollback/uninstall/recovery',
  'Document the result',
];
